{% set version = "0.4.0" %}
{% set variant = ("cuda" ~ cuda_compiler_version ~ "_") if cuda_compiler_version != "None" else "" %}
{% set variant = hoomd ~ "_" ~ variant %}

package:
  name: hoomd-dlext
  version: {{ version }}

source:
  url: https://github.com/SSAGESLabs/hoomd-dlext/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e7760f6e95aab21da7e1a9c4300a3b8e9f56cf14e22f9be47ae54d2efee24055

build:
  number: 0
  # Upstream package does not support Windows, Python < 3.6, or PyPy
  skip: true  # [win or py<36 or python_impl == "pypy"]
  skip: true  # [hoomd == "v2" and cuda_compiler_version != "None" and py>39]
  skip: true  # [hoomd == "v2" and cuda_compiler_version == "None" and py>310]
  skip: true  # [hoomd == "v3" and cuda_compiler_version not in ("11.2", "None")]
  string: {{ variant }}py{{ py }}_h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  ignore_run_exports_from:
    - tbb-devel

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - cmake >=3.16,!=3.23.0
    - make

  host:
    - python
    - pybind11
    - dlpack >=0.5
    - eigen             # [hoomd != "v2"]
    - hoomd ==2.9.6     # [hoomd == "v2" and cuda_compiler_version != "None"]
    - hoomd >=2.9.6,<3  # [hoomd == "v2" and cuda_compiler_version == "None"]
    - hoomd >=3.5,<4    # [hoomd == "v3"]
    - hoomd >=4         # [hoomd == "v4"]
    - tbb-devel

  run:
    - python
    - {{ pin_compatible('hoomd', upper_bound='2.9.7') }}  # [hoomd == "v2" and cuda_compiler_version != "None"]
    - {{ pin_compatible('hoomd', max_pin='x.x') }}        # [hoomd == "v2" and cuda_compiler_version == "None"]
    - {{ pin_compatible('hoomd', max_pin='x.x') }}        # [hoomd != "v2"]

test:
  imports:
    - hoomd.dlext

about:
  home: https://github.com/SSAGESLabs/hoomd-dlext
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: Wrapper for HOOMD-blue simulation data into DLPack data structures.

  description: |
    Provides access to HOOMD-blue simulation data on CPU or GPU via DLPack.
    This project is primarily designed to enable access to HOOMD-blue for
    the PySAGES project. At the moment, only HOOMD-blue version 2 is supported
    (support HOOMD-blue version 3 is in the works).

  doc_url: https://github.com/SSAGESLabs/hoomd-dlext
  dev_url: https://github.com/SSAGESLabs/hoomd-dlext

extra:
  recipe-maintainers:
    - pabloferz
    - nrouizem
